### ISSUE TITLE
Running on background?

### ISSUE THREAD

**Issue by mychaelgo** [gdxz123/pedometerSDK_fultter#1]
is it can be run on background? (even the app is suspended or closed)

**Comment by gdxz123** [comment]
iOS use data pull from  M7 or M8 sensor
Android also use data pull from sensor step count

**Comment by gdxz123** [comment]
> is it can be run on background? (even the app is suspended or closed)

iOS use data pull from M7 or M8 sensor
Android also use data pull from sensor step count
